now pip installable
StanfordMIMI/Comp2Comp pull request #20
Opened 2022-12-14 19:40 UTC by louisblankemeier

This seems to work for pip installation. @ad12 you would have a better sense of whether this is a workable solution.

2022-12-16 16:06 UTC, ad12 requested changes

2022-12-16 16:06 UTC, ad12 commented on setup.py
> +        "tensorflow",
```suggestion
        "tensorflow>=2.0.0",
```

2022-12-16 16:06 UTC, ad12 commented on setup.py
> +        "tensorflow",
We should mention that tensorflow should be installed before this library if users are looking for GPU support. TF install guides can be found here: https://www.tensorflow.org/install/pip

2022-12-17 21:32 UTC, louisblankemeier commented
Got it, can add to that doc that users should install tensorflow first if they are looking for GPU support. Will make sure to add this to a readthedocs when we start putting that together.

2022-12-20 07:07 UTC, merged